language: cpp
dist: bionic

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-9
          packages:
            - clang-9
            - libc++-9-dev
            - libc++abi-9-dev
            - libboost-atomic-dev
            - libboost-thread-dev
            - libboost-system-dev
            - libboost-date-time-dev
            - libboost-regex-dev
            - libboost-filesystem-dev
            - libboost-random-dev
            - libboost-chrono-dev
            - libboost-serialization-dev
            - libwebsocketpp-dev
            - openssl
            - libssl-dev
            - ninja-build
            - zlib1g-dev
      env:
        - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"
        - LINKER_FLAGS=""
before_install:
  - eval "${MATRIX_EVAL}"
  - git submodule update --init --recursive

script:
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXE_LINKER_FLAGS=${LINKER_FLAGS} .
  - cmake --build . -- VERBOSE=1